version: '3.8'

services:
  # PostgreSQL para o Keycloak
  postgres-keycloak:
    image: postgres:15
    container_name: dashboard-postgres-keycloak
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL para a aplicação Dashboard
  postgres-dashboard:
    image: postgres:15
    container_name: dashboard-postgres-dashboard
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dashboard_data:/var/lib/postgresql/data
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak para autenticação
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: dashboard-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dashboard-network:
    driver: bridge

volumes:
  postgres_keycloak_data:
  postgres_dashboard_data:
